### ISSUE TITLE
Improve instructions text

### ISSUE THREAD

**Issue by themichaelyang** [jkbren/stopgo#13]
- start instructions
- tour instructions, top info during tour

**Comment by themichaelyang** [comment]
Partially resolved by 8ebbde619406793159d8f0cb3c00df0083290c56. Top tour instructions improved, needs review.

**Comment by themichaelyang** [comment]
@shakty need to discuss Friday

**Comment by shakty** [comment]
I went through them, and made some changes. I believe they are fine now.
