### ISSUE TITLE
Red chooses, then is blue's turn, but Red screen is not updated. very confusing

### ISSUE THREAD

**Issue by shakty** [jkbren/stopgo#31]

**Comment by themichaelyang** [comment]
Resolved in 33fbe8f5a8d8789e0af946f373c51a11dacebc18

**Comment by shakty** [comment]
I don't think this is resolved. I mean that after Red choose it is unclear that he/she is actually waiting for the other player decision. It should be written somewhere on screen. Add the [loading dots](https://github.com/nodeGame/nodegame-window/blob/master/lib/modules/extra.js) to make the wait more "real".

**Comment by themichaelyang** [comment]
Resolved in e355e7aef4d073bb0f1d34c3fd75e23042930b29
