### ISSUE TITLE
end.htm is the same for interactive and tour -- end.htm should be refactored in interactive

### ISSUE THREAD

**Issue by shakty** [jkbren/stopgo#33]
Also in the interactive part says "you would have earned".

However, the whole page should be adapted to display the exit code and other information. So the changes to do are quite a few. To discuss together.

**Comment by shakty** [comment]
you could look at how this was implemented in this game:

- [html](https://github.com/nodeGame/imgscore/blob/heroku-likert/public/thankyou.htm)
- [player.js](https://github.com/nodeGame/imgscore/blob/heroku-likert/game/client_types/player.js)
- [logic.js](https://github.com/nodeGame/imgscore/blob/heroku-likert/game/client_types/logic.js)

Btw, this is a standard way of finishing an experiment, therefore it could be transformed into a widget, and also become a [Widget step](https://github.com/nodeGame/nodegame/wiki/Using-Widgets-v3#widget-steps)

**Comment by themichaelyang** [comment]
Widget is added, wait for node-widgets master to update

**Comment by themichaelyang** [comment]
I think this is updated? 

9061b55c606544c72b40e0131c9711dad47816c3
