### ISSUE TITLE
Font improvement

### ISSUE THREAD

**Issue by themichaelyang** [jkbren/stopgo#39]
Source Sans Pro looks a lot nicer than Helvetica Neue, and improves readability of the interface.

Helvetica Neue: | Source Sans Pro
----------------|-----------------
<img width="1280" alt="screen shot 2017-02-21 at 2 46 25 pm" src="https://cloud.githubusercontent.com/assets/4574958/23181844/8b308314-f844-11e6-8bda-950472bf965d.png">|<img width="1280" alt="screen shot 2017-02-21 at 2 42 19 pm" src="https://cloud.githubusercontent.com/assets/4574958/23181800/6286603c-f844-11e6-938c-0d3ce498a484.png">

**Comment by shakty** [comment]
I like the new font. A few questions before we switch.

- Is It a free font?
- How widespread it it across browsers? (we need it to look the same everywhere)
- What happens if a client does not have it?

**Comment by themichaelyang** [comment]
This is an [open source](https://github.com/adobe-fonts/source-sans-pro) + libre font by Adobe, released under the OFL, so we can use and distribute it freely. Additionally, its available over Google Fonts, so we wouldn't even have to host it ourselves.

The font would be served as a webfont, so it would be shown regardless of the client's font library. Webfonts have excellent support across browsers, but it would default to Helvetica / Arial if it is not loaded correctly (but Google Fonts is very fast).

**Comment by shakty** [comment]
Ok go ahead! But do you suggest to serve it locally or from google fonts?

**Comment by themichaelyang** [comment]
Up to you! But either is easy, although I think Google Fonts would be easier.

**Comment by shakty** [comment]
I think google fonts is easier too. However, I would include the font for reference in public/
