### ISSUE TITLE
Tour, Practice -> Tutorial

### ISSUE THREAD

**Issue by shakty** [jkbren/stopgo#42]
The practice part is named inconsistently "tour," or "practice," or "tutorial." Please change all occurrences to "tutorial." The change should affect both the instructions for the user, and the variable naming in the code.

**Comment by themichaelyang** [comment]
Should I add a short wait time as well?

**Comment by shakty** [comment]
what do you mean?

2017-04-13 10:40 GMT-04:00 Michael Yang <notifications@github.com>:

**Comment by themichaelyang** [comment]
Oops, wrong issue I commented on!

**Comment by themichaelyang** [comment]
Resolved in latest commit

**Comment by themichaelyang** [comment]
9061b55c606544c72b40e0131c9711dad47816c3
