### ISSUE TITLE
Tutorial Red Decision Screen is inconsistent with Real Game

### ISSUE THREAD

**Issue by shakty** [jkbren/stopgo#43]
The real game was updated so that the buttons are removed and waiting for the other player decision is appended. The tutorial should be consistent with this.

**Comment by themichaelyang** [comment]
Oh whoops. I mean't to leave that comment here @shakty. Should we add a short "wait" time in order to simulate the player waiting?

**Comment by shakty** [comment]
You could if u like.

However, I meant that the interface is not changed after the decision, e.g.
the buttons are not removed. This is a problem related to the fact that
there is code duplication between practice and game.

Am 13.04.2017 18:49 schrieb "Michael Yang" <notifications@github.com>:

**Comment by themichaelyang** [comment]
Yeah, we should find some way to abstract some of that code.

**Comment by themichaelyang** [comment]
Resolved in 1a8c40aa80d42f0f625e92d16f5cf194e0528510

**Comment by themichaelyang** [comment]
9061b55c606544c72b40e0131c9711dad47816c3
